version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      time: "14:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    commit-message:
      prefix: ":lock:"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "weekly"
      time: "14:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    commit-message:
      prefix: ":lock:"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
