labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in PSChristmasTree! 🎄

        Please follow these instructions, fill every question, and do every step. 🙏
        
        We're asking for this because answering questions and solving problems in GitHub takes a lot of time --
        this is time that we cannot spend on adding new features, fixing bugs, writing documentation or reviewing pull requests.

        By asking questions in a structured way (following this) it will be much easier for us to help you.

        There's a high chance that by following this process, you'll find the solution on your own, eliminating the need to submit a question and wait for an answer. 😎

        As there are many questions submitted every day, we will **DISCARD** and close the incomplete ones. 
        
        That will allow us (and others) to focus on helping people like you that follow the whole process. 🧑‍🎄
        
        Before opening a question, please check:
        - [PSChristmasTree documentation](https://pschristmastree.readthedocs.io/en/latest/)
        - [GitHub Discussions](https://github.com/Sofiane-77/PSChristmasTree/discussions)
        - [GitHub Issues](https://github.com/Sofiane-77/PSChristmasTree/issues)
  - type: checkboxes
    id: checks
    attributes:
      label: Checked other resources
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this question.
          required: true
        - label: I searched the PSChristmasTree documentation and discussions.
          required: true
        - label: I used the GitHub search to find a similar question and didn't find it.
          required: true
  - type: checkboxes
    id: help
    attributes:
      label: Commit to Help
      description: |
        After submitting this, I commit to one of:

          * Read open questions until I find 2 where I can help someone and add a comment to help there.
          * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
          * Once my question is answered, I will mark the answer as "accepted".
      options:
        - label: I commit to help with one of those options 👆
          required: true
  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, minimal, reproducible example with your use case (e.g., your PowerShell script or command).
        
        If a maintainer can copy it, run it, and see it right away, there's a much higher chance that you'll be able to get help.
        
        **Important!** 
        
        * Use code tags (e.g., ```powershell ... ```) to correctly format your code.
        * Reduce your code to the minimum required to reproduce the issue if possible. This makes it much easier for others to help you.
        * Avoid screenshots when possible, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.
      placeholder: |
        Show-PSChristmasTree -AnimationLoopNumber 5 -Colors @("Red","Green","Yellow")
      render: powershell
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What is the problem, question, or error?

        Write a short description explaining what you are doing, what you expect to happen, and what is currently happening.
      placeholder: |
        * I'm trying to use the `Show-PSChristmasTree` command to do X.
        * I expect to see Y.
        * Instead, it does Z.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: |
        Please share your system info with us. 
        
        - PowerShell version (run `$PSVersionTable.PSVersion`)
        - OS (Windows, Linux, macOS)
        - Any other relevant modules or settings
      placeholder: |
        PowerShell version: 7.2.0
        OS: Windows 10
        Other: ...
    validations:
      required: true
