labels: ["show-and-tell"]
body:
  - type: markdown
    attributes:
      value: |
        Share your creation or customization. Include code snippets or screenshots if you'd like.

  - type: textarea
    id: what_you_did
    attributes:
      label: What did you build or change?
      description: Briefly describe your work.
      placeholder: |
        Example: I added color gradients to the branches.

  - type: textarea
    id: feedback
    attributes:
      label: Are you seeking feedback?
      description: Let others know if you'd like comments or suggestions.